apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: ibm-entitlement-key
spec:
  encryptedData:
    .dockerconfigjson: AgAoyB/DgYx2UXlQx2fZoVhgP1Zsieq/xQsFFvyOaqRuBS3gQ5mfM10C1dRWBbpE5Qgn20FuPFlkv5YZFL9hqdrbrDO7aADNuwy9d4Ph9FzSfCTb/iIare/Dppr1RwLm7WzcLqeugvgvo5gFtqeGhtCkRbovyGZzmqP3cO7upktFkWYVmM2JeTJLCHhm8vp6wkZUbAlEC/WpoSZh9RDqP+3Gkip552xmiqkIlOXeHT2P+15oEedEtNqYhqu9FhBBobTkZuJNyDOO4lmHVNGNX3+IdGhqE9fnbMZcyS+mdOUPYSFYJE/dtyqXD+dwjSj6e9OeCpBCC+cK3keMdkzKlYq2FaYeoFOP20VIvQ/eFhl15+DhuBrD8fzuaAG9Y9YvkNZBzCWAc6bHN6qKfKPrnXsDvY9OaakmLduUIqTojjl264Z21Cg4iSCMFOZitKHfg6rtEePMdxjBen1oepQsvPwbyP9XDQ1swhfhJQpi+tHaF1SXRCdbOmO09cVHv5/SX+atZk0ABagN+VY1p1/Jeqs3DI1f0Hct8530PfV0Nb8db3sAqdPbGbzoZZ2SrVNih3QAOXjVnOjnR2aAiFA4iIPtnkh0DCX3ZZtjS+i2JlgtRDyLof3rT4HrbaUSEtUJ+MAVIFWrIbc72Fr12Sz61EkR5+TF7M3J3ECmxNX+a+yU0FFK/PgvjxW5Bpv60DfqqccF8JDCY4pcwlEV0HwW6V1kXyG05F850yqsO61uORW4xsWhN/pk0ly+aYFECkMYQ8oDYg97UHfQ1vFEFMk+/PiEwwrBgAJqBzIGDcptrcVzRa7LKlOPUcfFa5IDqI7r8taN2DFn2ETSh1yUkj3FZjNdAuOo3rqOW+ts86zlmzA1UybfhlXA4/Db97CSDkz8G03IzTae6oiIjxAy8a9Z7yGo9nk1GF1w8sadr646ll17hqSfcLWmXBMuKp+fhoHN3RU6GEIsmFbuDnOwfeZ28rLNntimi5lhT25k6oqcFlxX0FXjl4AGJZjWaWvpop4/wBwBztK5taakhSH63suYF6d79GehzzQnlw4J8ozPVASuqI/TSRmG3pVVQpxnl3hXxWsUjRha9atBgcVL4GDh2R9G7xQ0FAnM7/FE5I5PEcBoniftM6v2T80JhfTn7P3UMc+hO4Uyv70FiIh9/JAMkrD+A9Jswco+WT7KUaKOMtxZ0ZZcDMjwdbEaqru75N9Tsla5F1gdL5ouH3r6aiUWt69iVWqeDGPc30BSdx+8scVmZoJqRoOCL8eetwJThXpvVpfYdmIpgESa0orYjjWeKZ/0Ghy7wqbbPNAFA0I+6V4oKfY/28bB9bcz/hAivw7E70ftJZDlwn8ya7c+r/ee0JHYeZJMD/dd1e4A3hOM/9uC0T4uexIE
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      labels:
        created-by: pipeline
      name: ibm-entitlement-key
    type: kubernetes.io/dockerconfigjson

