apiVersion: appconnect.ibm.com/v1beta1
kind: Configuration
metadata:
  name: create-customer-policy
spec:
  type: policyproject
  contents: UEsDBAoAAAAAACi9aFQAAAAAAAAAAAAAAAAXABwAY3JlYXRlLWN1c3RvbWVyLXBvbGljeS9VVAkAA5vpJ2LN6SdidXgLAAEEYwAAAARjAAAAUEsDBBQACAAIACi9aFQAAAAAAAAAAPIAAAArABwAY3JlYXRlLWN1c3RvbWVyLXBvbGljeS9iYWNrZW5kdXJsLnBvbGljeXhtbFVUCQADm+knYpvpJ2J1eAsAAQRjAAAABGMAAABdjjsOwjAMhndOEWVvU7aq6mMBRqZygJAYiEidKE4LvT2pCkIwWfb/8Fd3z8GyCQIZhw3f5gVngMppg9eGn/pDVvKu3dTeWaMMULthbF1mto5+9pCcBGEHF4Og+Vs4yiEJZ6nugHoM9nPvYfBWxr/QUpyqyUm/R+2dwdjeYvSVEMstORNkhg4J1Bggj85ZymlSVVmUhXhQLX6yC6dYHyZ88eV/AVBLBwgyw5h4pAAAAPIAAABQSwECHgMKAAAAAAAovWhUAAAAAAAAAAAAAAAAFwAYAAAAAAAAABAA7UEAAAAAY3JlYXRlLWN1c3RvbWVyLXBvbGljeS9VVAUAA5vpJ2J1eAsAAQRjAAAABGMAAABQSwECHgMUAAgACAAovWhUMsOYeKQAAADyAAAAKwAYAAAAAAABAAAApIFRAAAAY3JlYXRlLWN1c3RvbWVyLXBvbGljeS9iYWNrZW5kdXJsLnBvbGljeXhtbFVUBQADm+knYnV4CwABBGMAAAAEYwAAAFBLBQYAAAAAAgACAM4AAABqAQAAAAA=
